config-version = 2

start-at-login = true

after-login-command = []
after-startup-command = []

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

automatically-unhide-macos-hidden-apps = false

persistent-workspaces = ['1', '2', '3', '4', '5']

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.right = 8
outer.top = 8
outer.bottom = 8

[mode.main.binding]
ctrl-alt-shift-cmd-h = 'focus left'
ctrl-alt-shift-cmd-j = 'focus down'
ctrl-alt-shift-cmd-k = 'focus up'
ctrl-alt-shift-cmd-l = 'focus right'

ctrl-alt-shift-cmd-1 = 'workspace 1'
ctrl-alt-shift-cmd-2 = 'workspace 2'
ctrl-alt-shift-cmd-3 = 'workspace 3'
ctrl-alt-shift-cmd-4 = 'workspace 4'
ctrl-alt-shift-cmd-5 = 'workspace 5'

cmd-alt-shift-h = 'move left'
cmd-alt-shift-j = 'move down'
cmd-alt-shift-k = 'move up'
cmd-alt-shift-l = 'move right'

cmd-alt-shift-1 = 'move-node-to-workspace 1'
cmd-alt-shift-2 = 'move-node-to-workspace 2'
cmd-alt-shift-3 = 'move-node-to-workspace 3'
cmd-alt-shift-4 = 'move-node-to-workspace 4'
cmd-alt-shift-5 = 'move-node-to-workspace 5'

ctrl-alt-shift-cmd-f = 'fullscreen'
cmd-alt-shift-f = 'layout floating tiling'
cmd-alt-shift-space = 'layout floating tiling'

ctrl-alt-shift-cmd-slash = 'layout tiles horizontal vertical'
ctrl-alt-shift-cmd-comma = 'layout accordion horizontal vertical'

cmd-alt-shift-minus = 'resize smart -50'
cmd-alt-shift-equal = 'resize smart +50'

ctrl-alt-shift-cmd-a = 'focus-back-and-forth'
ctrl-alt-shift-cmd-tab = 'workspace-back-and-forth'

cmd-alt-shift-q = 'close'

cmd-alt-shift-semicolon = 'flatten-workspace-tree'

cmd-alt-shift-leftSquareBracket = 'join-with left'
cmd-alt-shift-rightSquareBracket = 'join-with right'

ctrl-alt-shift-cmd-r = 'mode resize'
ctrl-alt-shift-cmd-b = 'exec-and-forget ~/.config/aerospace/layouts/tcl-shotts.sh'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
minus = 'resize smart -50'
equal = 'resize smart +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.calculator'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
check-further-callbacks = true
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.raycast.macos'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Stickies'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.colliderli.iina'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.KeyboardSetupAssistant'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.logi.optionsplus'
run = 'layout floating'
