[mgr]
cwd = { fg = "#a0a0a0" }
find_keyword = { fg = "#ffc799", bold = true }
find_position = { fg = "#99ffe4", italic = true }
marker_selected = { fg = "#ffc799", bg = "#232323" }
marker_copied = { fg = "#99ffe4", bg = "#232323" }
marker_cut = { fg = "#ff8080", bg = "#232323" }
border_symbol = "│"
border_style = { fg = "#282828" }
count_selected = { fg = "#101010", bg = "#ffc799" }
count_copied = { fg = "#101010", bg = "#99ffe4" }
count_cut = { fg = "#101010", bg = "#ff8080" }

[indicator]
current = { reversed = true }
preview = { reversed = true }

[tabs]
active = { fg = "#101010", bg = "#ffc799" }
inactive = { fg = "#a0a0a0", bg = "#282828" }

[mode]
normal_main = { fg = "#101010", bg = "#99ffe4", bold = true }
normal_alt = { fg = "#99ffe4", bg = "#161616" }
select_main = { fg = "#101010", bg = "#ffc799", bold = true }
select_alt = { fg = "#ffc799", bg = "#161616" }
unset_main = { fg = "#101010", bg = "#ff8080", bold = true }
unset_alt = { fg = "#ff8080", bg = "#161616" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#282828", bg = "#161616" }
progress_error = { fg = "#ff8080", bg = "#161616" }
perm_type = { fg = "#99ffe4" }
perm_read = { fg = "#ffc799" }
perm_write = { fg = "#ff8080" }
perm_exec = { fg = "#99ffe4" }
perm_sep = { fg = "#7d7d7d" }

[input]
border = { fg = "#282828" }
title = { fg = "#ffc799" }
value = { fg = "#ffffff" }
selected = { bg = "#232323" }

[pick]
border = { fg = "#282828" }
active = { fg = "#ffc799" }
inactive = { fg = "#a0a0a0" }

[tasks]
border = { fg = "#282828" }
title = { fg = "#ffc799" }
hovered = { fg = "#ffc799", underline = true }

[which]
mask = { bg = "#161616" }
cand = { fg = "#99ffe4" }
rest = { fg = "#7d7d7d" }
desc = { fg = "#a0a0a0" }
separator = "  "
separator_style = { fg = "#343434" }

[help]
on = { fg = "#99ffe4" }
run = { fg = "#a0a0a0" }
desc = { fg = "#7d7d7d" }
hovered = { bg = "#232323", bold = true }
footer = { fg = "#a0a0a0", bg = "#161616" }

[filetype]
rules = [
  { url = "*/", fg = "#99ffe4" },
  { is = "exec", fg = "#ffc799" },
  { is = "link", fg = "#b9aeda" },
  { is = "orphan", fg = "#ff8080" },
  { mime = "image/*", fg = "#e29eca" },
  { mime = "video/*", fg = "#e29eca" },
  { mime = "audio/*", fg = "#e29eca" },
  { mime = "application/zip", fg = "#ffc799" },
  { mime = "application/gzip", fg = "#ffc799" },
  { mime = "application/x-tar", fg = "#ffc799" },
  { mime = "application/x-bzip2", fg = "#ffc799" },
  { mime = "application/x-xz", fg = "#ffc799" },
  { mime = "application/x-7z-compressed", fg = "#ffc799" },
  { mime = "application/x-rar", fg = "#ffc799" },
  { mime = "application/pdf", fg = "#ff8080" },
  { mime = "application/doc", fg = "#90b99f" },
  { url = "*", fg = "#a0a0a0" },
]
