return {
  {
    "mason-org/mason.nvim",
    lazy = false,
    opts = {},
  },
  {
    "mason-org/mason-lspconfig.nvim",
    event = "VeryLazy",
    dependencies = {
      "mason-org/mason.nvim",
      "neovim/nvim-lspconfig",
    },
    opts = {
      automatic_enable = false,
      ensure_installed = require("config.servers").mason,
    },
  },
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    dependencies = { "mason-org/mason.nvim" },
    opts = {
      ensure_installed = {
        "prettierd",
        "oxfmt",
        "eslint_d",
        "stylua",
        "sql-formatter",
        "js-debug-adapter",
        "codelldb",
        "goimports",
        "gofumpt",
        "golangci-lint",
        "delve",
        "debugpy",
        "clang-format",
        "jdtls",
        "java-debug-adapter",
        "java-test",
        "vscode-spring-boot-tools",
        "tflint",
        "swiftlint",
        "ktlint",
        "kotlin-debug-adapter",
        "php-cs-fixer",
        "phpstan",
        "php-debug-adapter",
        "csharpier",
        "netcoredbg",
        "shfmt",
        "shellcheck",
        "hadolint",
        "ansible-lint",
        "bash-debug-adapter",
        "local-lua-debugger-vscode",
        "latexindent",
        "solhint",
      },
    },
  },
}
