gui:
  nerdFontsVersion: "3"
  sidePanelWidth: 0.28
  theme:
    activeBorderColor:
      # vesper
      - "#ffc799"
      - bold
      # mono
      # - "#EBEBEB"
      # - bold
    inactiveBorderColor:
      - "#505050"
    optionsTextColor:
      # vesper
      - "#99ffe4"
      # mono
      # - "#a0a0a0"
    selectedLineBgColor:
      - "#232323"
    defaultFgColor:
      - "#ffffff"
    unstagedChangesColor:
      # vesper
      - "#ff8080"
      # mono
      # - "#ec8989"
    searchingActiveBorderColor:
      # vesper
      - "#ffc799"
      - bold
      # mono
      # - "#EBEBEB"
      # - bold
    cherryPickedCommitBgColor:
      # vesper
      - "#ffcfa8"
      # mono
      # - "#343434"
    cherryPickedCommitFgColor:
      # vesper
      - "#99ffe4"
      # mono
      # - "#EBEBEB"
git:
  overrideGpg: false
  pagers:
    - pager: 'delta --paging=never --features=no-side-by-side --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"'
    - pager: 'delta --paging=never --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"'
customCommands:
  - key: "C"
    context: "files"
    description: "Conventional commit"
    prompts:
      - type: "menu"
        title: "Type"
        key: "Type"
        options:
          - name: "feat"
            value: "feat"
          - name: "fix"
            value: "fix"
          - name: "chore"
            value: "chore"
          - name: "refactor"
            value: "refactor"
          - name: "docs"
            value: "docs"
          - name: "test"
            value: "test"
          - name: "perf"
            value: "perf"
          - name: "ci"
            value: "ci"
      - type: "input"
        title: "Scope (optional)"
        key: "Scope"
      - type: "input"
        title: "Description"
        key: "Description"
    command: >-
      git commit -m "{{.Form.Type}}{{if .Form.Scope}}({{.Form.Scope}}){{end}}: {{.Form.Description}}"
    loadingText: "Committing..."
