shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer -m -p -r source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
fpath = "fpath=(\"{{ dir }}\" $fpath)\n"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
dir = "src"
apply = ["fpath"]

[plugins.compinit]
inline = '''
fpath=(${HOMEBREW_PREFIX:-/opt/homebrew}/share/zsh/site-functions $fpath)
autoload -Uz compinit
if [[ -n ${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh+24) ]]; then
  compinit
else
  compinit -C
fi
'''

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.forgit]
github = "wfxr/forgit"
apply = ["defer"]

[plugins.fzf-git]
github = "junegunn/fzf-git.sh"
apply = ["defer"]

[plugins.you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
apply = ["defer"]

[plugins.auto-notify]
github = "MichaelAquilina/zsh-auto-notify"
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
