local map = function(keys, func, desc)
  vim.keymap.set("n", keys, func, { buffer = true, desc = "Flutter: " .. desc })
end

map("<leader>lr", "<cmd>FlutterRun<cr>", "Run")
map("<leader>lq", "<cmd>FlutterQuit<cr>", "Quit")
map("<leader>lR", "<cmd>FlutterRestart<cr>", "Restart")
map("<leader>ll", "<cmd>FlutterReload<cr>", "Hot reload")
map("<leader>ld", "<cmd>FlutterDevices<cr>", "Devices")
map("<leader>le", "<cmd>FlutterEmulators<cr>", "Emulators")
map("<leader>lo", "<cmd>FlutterOutlineToggle<cr>", "Toggle outline")
map("<leader>ls", "<cmd>FlutterSuper<cr>", "Go to super class")
map("<leader>lD", "<cmd>FlutterDevTools<cr>", "Open DevTools")
map("<leader>lL", "<cmd>FlutterLogToggle<cr>", "Toggle log")
map("<leader>lc", "<cmd>FlutterLogClear<cr>", "Clear log")
map("<leader>lA", "<cmd>FlutterReanalyze<cr>", "Reanalyze")
map("<leader>ln", "<cmd>FlutterRename<cr>", "Rename (update imports)")
