return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    spec = {
      { "<leader>f", group = "find" },
      { "<leader>t", group = "toggle" },
      { "<leader>c", group = "code" },
      { "<leader>d", group = "debug" },
      { "<leader>s", group = "swap" },
      { "<leader>x", group = "diagnostics" },
      { "<leader>a", group = "ai" },
      { "<leader>b", group = "buffer" },
      { "<leader>h", group = "harpoon" },
      { "<leader>g", group = "git" },
      { "<leader>gh", group = "hunks" },
      { "<leader>q", group = "session" },
      { "<leader>n", group = "test" },
      { "<leader>r", group = "replace" },
      { "<leader>o", group = "tasks" },
      { "<leader>R", group = "rest" },
      { "<leader>j", group = "java" },
      { "<leader>m", group = "scala" },
      { "<leader>w", group = "windows" },
      { "<leader>E", group = "env" },
    },
  },
}
